# Generated by Django 4.2.9 on 2024-04-03 12:06

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Devices',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('device_id', models.CharField(max_length=100)),
                ('device_name', models.CharField(max_length=100)),
                ('device_type', models.CharField(max_length=100)),
                ('device_status', models.CharField(max_length=100)),
                ('device_online', models.BooleanField()),
                ('device_timezone', models.CharField(max_length=100)),
                ('device_dps', models.JSONField()),
                ('device_icon', models.CharField(max_length=100)),
                ('device_category', models.CharField(max_length=100)),
                ('device_sub_id', models.CharField(max_length=100)),
                ('device_sub_type', models.CharField(max_length=100)),
                ('device_sub_dps', models.JSONField()),
                ('device_sub_icon', models.CharField(max_length=100)),
                ('device_sub_category', models.CharField(max_length=100)),
                ('device_sub_online', models.BooleanField()),
                ('device_sub_timezone', models.CharField(max_length=100)),
                ('device_sub_status', models.CharField(max_length=100)),
                ('device_sub_name', models.CharField(max_length=100)),
                ('device_sub', models.BooleanField()),
            ],
            options={
                'verbose_name': 'Device',
                'verbose_name_plural': 'Devices',
            },
        ),
    ]
