# Generated by Django 4.2.9 on 2024-04-10 17:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tuya_smart_home_devices', '0010_device_is_active'),
    ]

    operations = [
        migrations.AlterField(
            model_name='device',
            name='id',
            field=models.CharField(max_length=50, primary_key=True, serialize=False, unique=True),
        ),
    ]
