# Generated by Django 4.2.9 on 2024-04-10 17:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tuya_smart_home_devices', '0011_alter_device_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='device',
            name='ip',
            field=models.CharField(blank=True, null=True),
        ),
    ]
