# Generated by Django 4.2.9 on 2024-02-19 16:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0004_userprofile_expire_date_userprofile_otp_used_at'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userprofile',
            name='expire_date',
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='otp_created_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
