# Generated by Django 4.2.9 on 2024-02-19 16:45

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0005_remove_userprofile_expire_date_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userprofile',
            name='otp_used_at',
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='otp_created_at',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
