# Generated by Django 4.2.9 on 2024-02-24 09:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0007_userprofile_is_rental_owner_userprofile_is_tenant'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='iser_profile_pic',
            field=models.FileField(blank=True, null=True, upload_to='profile_pics'),
        ),
    ]
