# Generated by Django 4.2.9 on 2024-06-04 16:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0011_alter_userprofile_phone'),
    ]

    operations = [
        migrations.RenameField(
            model_name='userprofile',
            old_name='is_rental_owner',
            new_name='is_client',
        ),
    ]
