# Generated by Django 4.2.9 on 2024-04-07 08:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tuya_smart_home', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='devices',
            name='device_category',
        ),
        migrations.RemoveField(
            model_name='devices',
            name='device_dps',
        ),
        migrations.RemoveField(
            model_name='devices',
            name='device_icon',
        ),
        migrations.RemoveField(
            model_name='devices',
            name='device_online',
        ),
        migrations.RemoveField(
            model_name='devices',
            name='device_status',
        ),
        migrations.RemoveField(
            model_name='devices',
            name='device_sub',
        ),
        migrations.RemoveField(
            model_name='devices',
            name='device_sub_category',
        ),
        migrations.RemoveField(
            model_name='devices',
            name='device_sub_dps',
        ),
        migrations.RemoveField(
            model_name='devices',
            name='device_sub_icon',
        ),
        migrations.RemoveField(
            model_name='devices',
            name='device_sub_id',
        ),
        migrations.RemoveField(
            model_name='devices',
            name='device_sub_name',
        ),
        migrations.RemoveField(
            model_name='devices',
            name='device_sub_online',
        ),
        migrations.RemoveField(
            model_name='devices',
            name='device_sub_status',
        ),
        migrations.RemoveField(
            model_name='devices',
            name='device_sub_timezone',
        ),
        migrations.RemoveField(
            model_name='devices',
            name='device_sub_type',
        ),
        migrations.RemoveField(
            model_name='devices',
            name='device_timezone',
        ),
        migrations.RemoveField(
            model_name='devices',
            name='device_type',
        ),
        migrations.AddField(
            model_name='devices',
            name='category',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='devices',
            name='category_name',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='devices',
            name='create_time',
            field=models.IntegerField(null=True),
        ),
        migrations.AddField(
            model_name='devices',
            name='gateway_id',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='devices',
            name='icon',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='devices',
            name='ip',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='devices',
            name='lat',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='devices',
            name='local_key',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='devices',
            name='lon',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='devices',
            name='model',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='devices',
            name='online',
            field=models.BooleanField(null=True),
        ),
        migrations.AddField(
            model_name='devices',
            name='product_id',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='devices',
            name='product_name',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='devices',
            name='sub',
            field=models.BooleanField(null=True),
        ),
        migrations.AddField(
            model_name='devices',
            name='time_zone',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='devices',
            name='update_time',
            field=models.IntegerField(null=True),
        ),
        migrations.AddField(
            model_name='devices',
            name='uuid',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='devices',
            name='device_id',
            field=models.CharField(max_length=100, unique=True),
        ),
        migrations.AlterField(
            model_name='devices',
            name='device_name',
            field=models.CharField(max_length=100, null=True),
        ),
    ]
