# Generated by Django 4.2.9 on 2024-04-10 09:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tuya_smart_home', '0007_rename_device_id_mydevices_device_id'),
    ]

    operations = [
        migrations.RenameField(
            model_name='mydevices',
            old_name='device_id',
            new_name='device',
        ),
    ]
