# Generated by Django 4.2.9 on 2024-04-10 10:02

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('tuya_smart_home', '0008_rename_device_id_mydevices_device'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mydevices',
            name='device',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='my_device', to='tuya_smart_home.device', unique=True),
        ),
    ]
