# Generated by Django 4.2.9 on 2024-04-11 13:55

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('tuya_smart_home', '0012_alter_device_ip'),
    ]

    operations = [
        migrations.CreateModel(
            name='SmartLockCard',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('card_id', models.CharField(blank=True, max_length=50, null=True)),
                ('card_number', models.CharField(blank=True, max_length=50, null=True)),
                ('card_type', models.CharField(blank=True, max_length=50, null=True)),
                ('create_time', models.BigIntegerField(blank=True, null=True)),
                ('end_time', models.BigIntegerField(blank=True, null=True)),
                ('start_time', models.BigIntegerField(blank=True, null=True)),
                ('device_id', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='tuya_smart_home.device')),
                ('tenant_id', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Smart Lock Card',
                'verbose_name_plural': 'Smart Lock Cards',
            },
        ),
    ]
