# Generated by Django 4.2.9 on 2024-04-18 07:03

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('tuya_smart_home', '0014_rentalownerhomedevices_rentalownerproperty_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='RentalOwnerPropertyDevices',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('create_time', models.BigIntegerField(blank=True, null=True)),
                ('device_id', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='tuya_smart_home.device')),
            ],
            options={
                'verbose_name': 'Property Device',
                'verbose_name_plural': 'Property Devices',
            },
        ),
        migrations.CreateModel(
            name='TenantPropertyDevices',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('create_time', models.BigIntegerField(blank=True, null=True)),
                ('device', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='tenant_property_device', to='tuya_smart_home.device', unique=True)),
            ],
            options={
                'verbose_name': 'Tenant Property Device',
                'verbose_name_plural': 'Tenant Property Devices',
            },
        ),
        migrations.RemoveField(
            model_name='tenanthomedevices',
            name='device',
        ),
        migrations.RemoveField(
            model_name='tenanthomedevices',
            name='home_id',
        ),
        migrations.RemoveField(
            model_name='tenanthomedevices',
            name='user_id',
        ),
        migrations.AlterModelOptions(
            name='rentalownerproperty',
            options={'verbose_name': 'Property', 'verbose_name_plural': 'Properties'},
        ),
        migrations.AlterModelOptions(
            name='tenantroomdevices',
            options={'verbose_name': 'Tenant Device', 'verbose_name_plural': 'Tenant Devices'},
        ),
        migrations.RenameField(
            model_name='rentalownerpropertyroom',
            old_name='home_id',
            new_name='property_id',
        ),
        migrations.AlterField(
            model_name='rentalownerproperty',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='property_images/'),
        ),
        migrations.AlterField(
            model_name='tenantroomdevices',
            name='device',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='tenant_room_device', to='tuya_smart_home.device', unique=True),
        ),
        migrations.DeleteModel(
            name='RentalOwnerHomeDevices',
        ),
        migrations.DeleteModel(
            name='TenantHomeDevices',
        ),
        migrations.AddField(
            model_name='tenantpropertydevices',
            name='property_id',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='tuya_smart_home.rentalownerproperty'),
        ),
        migrations.AddField(
            model_name='tenantpropertydevices',
            name='user_id',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='rentalownerpropertydevices',
            name='property_id',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='tuya_smart_home.rentalownerproperty'),
        ),
    ]
