# Generated by Django 4.2.9 on 2024-04-18 08:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tuya_smart_home', '0015_rentalownerpropertydevices_tenantpropertydevices_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='rentalownerproperty',
            name='create_time',
        ),
        migrations.RemoveField(
            model_name='rentalownerproperty',
            name='update_time',
        ),
    ]
