# Generated by Django 4.2.9 on 2024-04-18 09:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tuya_smart_home', '0017_rentalownerproperty_create_time_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='rentalownerproperty',
            name='district',
        ),
    ]
