# Generated by Django 4.2.9 on 2024-04-18 11:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tuya_smart_home', '0018_remove_rentalownerproperty_district'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='rentalownerpropertyroomtype',
            name='create_time',
        ),
        migrations.RemoveField(
            model_name='rentalownerpropertyroomtype',
            name='update_time',
        ),
    ]
