# Generated by Django 4.2.9 on 2024-04-20 10:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tuya_smart_home', '0020_rentalownerpropertyroomtype_create_time_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='rentalownerpropertyroom',
            name='create_time',
        ),
        migrations.RemoveField(
            model_name='rentalownerpropertyroom',
            name='update_time',
        ),
    ]
