# Generated by Django 4.2.9 on 2024-04-20 10:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tuya_smart_home', '0021_remove_rentalownerpropertyroom_create_time_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='rentalownerpropertyroom',
            name='create_time',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
        migrations.AddField(
            model_name='rentalownerpropertyroom',
            name='update_time',
            field=models.DateTimeField(auto_now=True, null=True),
        ),
    ]
