# Generated by Django 4.2.9 on 2024-04-20 14:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tuya_smart_home', '0023_remove_rentalownerpropertydevices_create_time'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='rentalownerpropertydevices',
            unique_together={('device_id', 'property_id')},
        ),
    ]
