# Generated by Django 4.2.9 on 2024-04-20 14:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tuya_smart_home', '0024_alter_rentalownerpropertydevices_unique_together'),
    ]

    operations = [
        migrations.AddField(
            model_name='rentalownerpropertydevices',
            name='create_time',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
    ]
