# Generated by Django 4.2.9 on 2024-04-20 14:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tuya_smart_home', '0025_rentalownerpropertydevices_create_time'),
    ]

    operations = [
        migrations.AlterField(
            model_name='rentalownerpropertydevices',
            name='create_time',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
